apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
 type: LoadBalancer
 selector:
   app: dev
 ports:
   - name: http
     protocol: TCP
     port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
       - name: apache
         image: kanagarasu/apach:latest
         ports:
          - containerPort: 80
